# Generated by Django 6.1.1 on 2026-09-25 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={
                "ordering": ["pk"],
                "verbose_name": "worker",
                "verbose_name_plural": "workers",
            },
        ),
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workers",
                to="tasks.position",
            ),
        ),
    ]
